<?php
defined('ABSPATH') OR exit('No direct script access allowed');

/*
|---------------------------------------------------------------------- 
| DoobleGniter: Remove All Default Image Sizes Except Thumbnail
|---------------------------------------------------------------------- 
| 
| This function hooks into the `intermediate_image_sizes_advanced` filter 
| to remove all default image sizes provided by WordPress, except for the 
| 'thumbnail'. It keeps only the thumbnail size while removing sizes such as 
| 'medium', 'large', 'full', and any other custom sizes you specify. 
|
| The goal is to reduce the number of image sizes generated by WordPress and 
| keep only the ones necessary for the theme's requirements.
|
*/
function DoobleGniter_remove_default_image_sizes( $sizes ) {
    // Keep only the 'thumbnail' size and remove the rest
    unset($sizes['medium']);
    unset($sizes['medium_large']);
    unset($sizes['large']);
    unset($sizes['full']);
    
    // Optionally, you can add more sizes to remove
    // unset($sizes['custom_size']); // Replace 'custom_size' with any custom sizes to remove

    return $sizes;
}
add_filter('intermediate_image_sizes_advanced', 'DoobleGniter_remove_default_image_sizes');

/*
|---------------------------------------------------------------------- 
| DoobleGniter: Add Custom Image Sizes
|---------------------------------------------------------------------- 
| 
| This function is used to add custom image sizes to WordPress. 
| You can specify different width, height, and cropping behavior for each size.
|
| The function is hooked to `after_setup_theme` to ensure it runs 
| when the theme is fully initialized.
|
| Example sizes:
| - 'custom_size_1': A hard-cropped image size of 800x600 pixels.
| - 'custom_size_2': A soft-cropped image size of 1200x800 pixels.
|
| You can add more sizes as needed based on your theme's design requirements.
|
*/
function DoobleGniter_add_custom_image_sizes() {
    // Example of adding a custom image size: 'custom_size_1'
    add_image_size('custom_size_1', 800, 600, true);  // 800px wide by 600px tall, hard crop

    // Example of adding another custom size: 'custom_size_2'
    add_image_size('custom_size_2', 1200, 800, false);  // 1200px wide by 800px tall, soft crop

    // Add more sizes as needed
}
add_action('after_setup_theme', 'DoobleGniter_add_custom_image_sizes');